-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgI+NyyCGpOC9DZ0gnDdhx2p11ZhXHtyWB2YmfX5g5XjCgCgYIKoZIzj0DAQehRANCAAT2Qinwg0mfQeiTgCcOHzxAUCHhYiiV/oYG66d3gbcPx8XskQD6FBu+tvK5rsxGZO5JCxypjBc/jrInI3ULgZBs
-----END PRIVATE KEY-----